addons:
  apt:
    sources:
      - google-chrome
    packages:
      - google-chrome-stable
language: node_js
node_js:
  - 12
jobs:
  before-install:
    - cd front
  install:
    - npm install
  script:
    - npm run test:unit
    - npm run test:e2e
