sudo: required
cache:
  directories:
    - front/node_modules
addons:
  chrome: stable
language: node_js
node_js:
  - 12
jobs:
  before-install:
    - cd front
  install:
    - npm install
  before-script:
    - npm run dev &
  script:
    - npm run test:unit
    - sleep 15
    - xvfb-run npm run test:e2e
