sudo: required

cache:
  directories:
    - front/node_modules

language: node_js
node_js: 12

jobs:
  before-install:
    - cd front
  install:
    - npm install
    - sudo apt install python3-dev libpq-dev
  script:
    - npm run test:unit
  after-script:
    - npm run generate

deploy:
  provider: heroku
  api_key:
    secure: $HEROKU_KEY
  app: thefuntains
  skip_cleanup: true
