sudo: required
cache:
  directories:
    - front/node_modules
addons:
  chrome: stable
language: node_js
node_js:
  - 12
jobs:
  before-install:
    - cd front
  install:
    - npm install
  before-script:
    - npm run build
    - npm run start &
  script:
    - npm run test:unit
    - sleep 15
    - xvfb-run npm run test:e2e
deploy:
  provider: heroku
  api_key:
    secure: $HEROKU_KEY
  app: thefuntains
  skip_cleanup: true
  run:
    - cd front
    - npm run generate
    - cd ..
    - pip install -r requirements.txt
    - python manage.py runserver
