# Generated by Django 3.1 on 2020-08-27 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('worker', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='salary',
            name='preference',
            field=models.CharField(choices=[(0, 'morning'), (1, 'evening')], max_length=20),
        ),
        migrations.DeleteModel(
            name='Preference',
        ),
    ]
