# Generated by Django 3.1 on 2020-08-27 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('worker', '0002_auto_20200827_1507'),
    ]

    operations = [
        migrations.AlterField(
            model_name='salary',
            name='name',
            field=models.CharField(max_length=30, unique=True),
        ),
    ]
