# Generated by Django 3.1 on 2020-08-27 17:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('worker', '0003_auto_20200827_1518'),
    ]

    operations = [
        migrations.AlterField(
            model_name='salary',
            name='preference',
            field=models.CharField(choices=[('morning', 0), ('evening', 1)], max_length=20),
        ),
    ]
