# Generated by Django 3.1 on 2020-08-27 17:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('worker', '0004_auto_20200827_1711'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Salary',
            new_name='Employee',
        ),
    ]
