# Generated by Django 3.1 on 2020-09-06 17:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('worker', '0006_day'),
    ]

    operations = [
        migrations.CreateModel(
            name='WorkDay',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start', models.IntegerField()),
                ('end', models.IntegerField()),
                ('day', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='worker.day')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='worker.employee')),
            ],
        ),
        migrations.AddField(
            model_name='day',
            name='employee',
            field=models.ManyToManyField(through='worker.WorkDay', to='worker.Employee'),
        ),
    ]
