# Generated by Django 3.1 on 2020-09-23 13:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('worker', '0009_auto_20200910_1413'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='workday',
            name='end',
        ),
        migrations.RemoveField(
            model_name='workday',
            name='start',
        ),
    ]
