# Generated by Django 3.1 on 2020-09-23 13:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('worker', '0009_auto_20200910_1413'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workday',
            name='end',
            field=models.TimeField(),
        ),
        migrations.AlterField(
            model_name='workday',
            name='start',
            field=models.TimeField(),
        ),
    ]
