# Generated by Django 3.1 on 2020-09-23 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('worker', '0010_auto_20200923_1548'),
    ]

    operations = [
        migrations.AddField(
            model_name='workday',
            name='end',
            field=models.TimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='workday',
            name='start',
            field=models.TimeField(auto_now=True),
        ),
    ]
