# Generated by Django 3.1 on 2020-09-25 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('worker', '0011_auto_20200923_1548'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workday',
            name='end',
            field=models.TimeField(),
        ),
        migrations.AlterField(
            model_name='workday',
            name='start',
            field=models.TimeField(),
        ),
    ]
