# Generated by Django 3.1 on 2020-09-25 12:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('worker', '0014_auto_20200925_1411'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='workday',
            name='end',
        ),
        migrations.RemoveField(
            model_name='workday',
            name='start',
        ),
    ]
