# Generated by Django 3.1 on 2020-09-27 17:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('worker', '0017_auto_20200927_1927'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employee',
            name='off',
        ),
    ]
