# Generated by Django 3.1 on 2020-09-27 17:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('worker', '0018_remove_employee_off'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='off',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='worker.week'),
        ),
    ]
