# Generated by Django 3.1 on 2020-09-28 10:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('worker', '0019_auto_20200927_2006'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employee',
            name='off',
        ),
    ]
