# Generated by Django 3.1 on 2020-09-30 17:05

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('worker', '0023_auto_20200930_1904'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='off',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(choices=[('monday', 0), ('tuesday', 1), ('wednesday', 2), ('thursday', 3), ('friday', 4), ('saturday', 5), ('sunday', 6)], max_length=30, null=True), blank=True, default=list, size=None),
        ),
    ]
